# Site settings
title: Paras Parkash
email: parasxparkash@gmail.com
description: >-
  My work focuses on developing quantitative risk management models leveraging agentic AI that dynamically manage market risks and optimize portfolio protection, using derivatives combined with advanced volatility models like GARCH, Heston, and higher-order frameworks.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parasparkash.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Collections
collections:
  notes:
    output: true
    permalink: /notes/:name/

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      author: Paras Parkash
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: note

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - template copy.html

# Include hidden directories to be served (for Chrome DevTools request)
include:
  - .well-known

# Site data
author:
  name: Paras Parkash
  email: parasxparkash@gmail.com
  location: Chennai, India
  github: parasxparkash
  linkedin: parasxparkash
  twitter: parasxparkash
  medium: https://medium.com/@parasparkash
  substack: https://parasparkash.substack.com
  scholar: https://scholar.google.com/citations?user=
  orcid: https://orcid.org/
  kaggle: https://kaggle.com/
  researchgate: https://www.researchgate.net/profile/
  stackoverflow: https://stackoverflow.com/users/
  youtube: https://www.youtube.com/@
  rss: /feed.xml

# MathJax settings
mathjax: true

# SEO Settings
seo:
  type: "Person"
  name: "Paras Parkash"
  description: "Quantitative Researcher specializing in derivatives, risk management, and AI-powered financial models"
  image: "/assets/profile-optimized.webp"
  url: "https://parasparkash.github.io"
  twitter:
    username: "parasxparkash"
  facebook:
    app_id: ""
  google_site_verification: ""
  bing_site_verification: ""
  yandex_site_verification: ""

# Sitemap settings
sitemap:
  changefreq: weekly
  priority: 0.7
  lastmod: true

# Feed settings
feed:
  path: feed.xml
  excerpt_only: true
  limit: 20

# Timezone
timezone: Asia/Kolkata

# Encoding
encoding: utf-8

# Permalinks
permalink: /:categories/:year/:month/:day/:title/
